// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqpJawtW8xVG_P-YGYSIYcAd8frZbbqLY',
    appId: '1:278338491148:web:f483866327e0fd4654ef29',
    messagingSenderId: '278338491148',
    projectId: 'tanara-25a3c',
    authDomain: 'tanara-25a3c.firebaseapp.com',
    databaseURL: 'https://tanara-25a3c-default-rtdb.firebaseio.com',
    storageBucket: 'tanara-25a3c.appspot.com',
    measurementId: 'G-RKZMGHGYST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPd8nl5XJqgrDb_n-W7cdVpvXRVPWcHBc',
    appId: '1:278338491148:android:bde2b82829108d3054ef29',
    messagingSenderId: '278338491148',
    projectId: 'tanara-25a3c',
    databaseURL: 'https://tanara-25a3c-default-rtdb.firebaseio.com',
    storageBucket: 'tanara-25a3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqKgZ7Dp0qAYaWhjnhR5OqBsac1qamgg',
    appId: '1:278338491148:ios:5f701a1d13c1630454ef29',
    messagingSenderId: '278338491148',
    projectId: 'tanara-25a3c',
    databaseURL: 'https://tanara-25a3c-default-rtdb.firebaseio.com',
    storageBucket: 'tanara-25a3c.appspot.com',
    iosBundleId: 'com.example.tanara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvqKgZ7Dp0qAYaWhjnhR5OqBsac1qamgg',
    appId: '1:278338491148:ios:e26e1ca74dad757854ef29',
    messagingSenderId: '278338491148',
    projectId: 'tanara-25a3c',
    databaseURL: 'https://tanara-25a3c-default-rtdb.firebaseio.com',
    storageBucket: 'tanara-25a3c.appspot.com',
    iosBundleId: 'com.example.tanara.RunnerTests',
  );
}
